### ISSUE TITLE
twos complement broken

### ISSUE THREAD

**Issue by theDogOfPavlov** [brettmarl/node-ina219#2]
https://github.com/brettmarl/node-ina219/blob/f5722c6f50280abbc8ed6c5860475af769dc7b13/ina219.js#L168

Hi, the shift right on line 168 should actually be a shift left. After the fix the library correctly reports negative currents correctly ...

**Comment by eliotlandrum** [comment]
@theDogOfPavlov - FYI - I'm currently using this library on a little project and have found a few things to fix. I haven't pushed a PR up to this yet as I'm not done testing, but my changes are in my fork.

**Comment by brettmarl** [comment]
Cool - thanks. Feel free to have at it. :)

**Comment by Laserlicht** [comment]
Hi,

this issue should fixed in this repo.
The npm version should be bug-free. :)

**Comment by aplikatika** [comment]
@brettmarl Thank you for accepting the pull request so quickly! May we upgrade the npm package version to 0.6.2 and publish? Also, this issue can be closed now.

**Comment by brettmarl** [comment]
fixed. updated package and re-published. thanks @aplikatika
