### ISSUE TITLE
How to Handle Read Errors

### ISSUE THREAD

**Issue by msi-matthew** [brettmarl/node-ina219#4]
I have a function that is reading the voltage on a continuous loop polling every 20 ms. A lot of the times the loop successfully exits without error, but I often get 

`
~/node_modules/i2c-bus/i2c-bus.js:355 . 
return i2c.readI2cBlockSync(peripheralSync(this, addr), cmd, length, buffer);  
             ^  
Error: , Remote I/O error  
    at Bus.readI2cBlockSync (~/node_modules/i2c-bus/i2c-bus.js:355:14)  
    at Ina219.readRegister (~/node_modules/ina219/ina219.js:184:12)  
    at Ina219.getShuntVoltage_raw (~/node_modules/ina219/ina219.js:448:7)  
    at Ina219.getShuntVoltage_mV (~/node_modules/ina219/ina219.js:500:7)  
    at Timeout.setInterval [as _onTimeout] (~/test_run.js:37:14)  
    at ontimeout (timers.js:498:11)  
    at tryOnTimeout (timers.js:323:5)  
    at Timer.listOnTimeout (timers.js:290:5)  
`

Do you know why this error might be happening so often?

What would be a good way to catch this error and restart the loop read?

I am running on a Raspberry Pi...

**Comment by msi-matthew** [comment]
I am trying to run this until `switch GPIO state`, and set `iteration = 0` if `i2c-bus` throws an error. 

    const MAX_ITERATIONS = 15
    const DELAY_MS = 15
    let iteration = 0

    const MIN_READS = 110
    let reads = 0

    let getVoltage = ina219.calibrate32V1A.bind(() => {
      let int = setInterval(() => {
        ina219.getShuntVoltage_mV((volts) => {
          if (volts > 9) iteration = 0 // Reset the counter
          else {
            iteration++
            reads++
          }
        })
        if (iteration >= MAX_ITERATIONS && reads > MIN_READS) {
          clearInterval(int)
          // switch GPIO state
        }
      }, DELAY_MS)
    })

**Comment by msi-matthew** [comment]
I think the problem is related to this: https://github.com/fivdi/i2c-bus/issues/36

http://www.advamation.com/knowhow/raspberrypi/rpi-i2c-bug.html

**Comment by msi-matthew** [comment]
Would rewriting `readRegister`, `Ina219.getShuntVoltage_raw`, and `Ina219.getShuntVoltage_mV` with the following try/catch pattern prevent this error?

https://github.com/fivdi/i2c-bus/blob/master/example/i2cscan.js

**Comment by msi-matthew** [comment]
I still have issues when wrapping the code in a try-catch block. 

    const ina219 = require('ina219')
    const DELAY_MS = 15
    
    try {
      let getVoltage = ina219.calibrate32V1A(() => {
        let int = setInterval(() => {
          ina219.getShuntVoltage_mV((volts) => {
            console.log(volts)
          })
        }, DELAY_MS)
      })
    }
    catch (error) {
      console.log(error)
    }

> /home/pi/Documents/node_modules/i2c-bus/i2c-bus.js:355 return 
> i2c.readI2cBlockSync(peripheralSync(this, addr), cmd, length, buffer);
> Error: , Communication error on send

**Comment by brettmarl** [comment]
Hey Matthew - sorry you are having trouble with this. I didn't write the base library - I simply took the Adafruit C++ driver from here (https://github.com/adafruit/Adafruit_INA219) and ported it to run in Node.js. That was quite some time ago - and there may have been fixes in the base library that I haven't incorporated. It worked for my needs at the time, and I shared on GitHub hoping it would save someone else the time. I don't have bandwidth to investigate why it's not working for you use-case - but feel free to look at the original library and modify the code as you see fit and submit a PR.

**Comment by msi-matthew** [comment]
Yep, no problem. Thank you for the good work!! Just documenting as much as possible in case it would help someone in the future. 

As suggested by @fivdi both the calibrate and getVoltage functions have their own error scope, therefore to catch read/write error after the device has been calibrated one can process as follows:

```
const ina219 = require('ina219')
const DELAY_MS = 15

let getVoltage = ina219.calibrate32V1A(() => {
  let int = setInterval(() => {
    try {
      ina219.getShuntVoltage_mV((volts) => {
        console.log(volts)
      })
    } catch (ignore) {
      console.log('ignoring error thrown by getShuntVoltage_mV')
    }
  }, DELAY_MS)
})
